# Generated by Django 3.2.7 on 2021-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True, verbose_name='Url_mail')),
                ('email', models.EmailField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('allow_data_process', models.BooleanField(blank=True, default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-created_at'],
            },
        ),
    ]
