# Generated by Django 3.2.7 on 2021-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='allow_data_process',
            field=models.BooleanField(blank=True, default=False, verbose_name='Разрешение на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url_mail'),
        ),
    ]
